Flake8 pyi
nutti/fake-bpy-module pull request #296
Opened 2024-07-30 20:15 UTC by JonathanPlasse

### Purpose of the pull request

*The purpose of the pull request. (e.g. Fix Bug, Feature request)*

### Description about the pull request

*The description about this pull request.*

### Additional comments** [Optional]

2024-08-12 05:01 UTC, nutti reviewed
@JonathanPlasse 

Does this PR relate to https://github.com/nutti/fake-bpy-module/issues/161#issue-2045306391 ?

> Add Ruff and enable linter rules to avoid regression we encountered

If this PR supports the above item, could you add the new linter test for the generated code in CI pipeline?

2024-08-15 15:17 UTC, JonathanPlasse commented
> could you add the new linter test for the generated code in CI pipeline?

I added flake8-pyi to run in the CI.
I ignore 5 rules `PYI011`, `PYI014`, `PYI018`, `PYI021`, `PYI054`.
They need to be ignored otherwise the CI fails (c.f. https://github.com/nutti/fake-bpy-module/actions/runs/10405883813/job/28817692685`)
![Screenshot from 2024-08-15 17-16-18](https://github.com/user-attachments/assets/e5824f94-d612-433c-a8df-e7a7cdd0671c)

These ignored rules could be addressed in follow-up PRs.

2024-08-16 09:15 UTC, nutti requested changes

2024-08-16 09:15 UTC, nutti commented on .github/workflows/fake-bpy-module-ci.yml
> +      - name: Run Ruff flake8-pyi checks
The generated code can be found at the path `raw_modules/fake_bpy_module*` as zip files.
Extract them to the some temporary directories and lint them is better which tests the artifacts itself.

2024-08-16 09:15 UTC, nutti commented on tools/pip_package/build_pip_package.sh
> -rm -rf "${tmp_dir}"
If you lint the artifact, this change is not required any more.

2024-08-18 00:23 UTC, nutti requested changes
Thank you for the changes.
I left some trivial comments.
Could you apply them?

2024-08-18 00:23 UTC, nutti commented on tools/pip_package/run_ruff_flake8_pyi.sh
> +ZIP_PATH=$(find . -name "$ZIP_FILE" -print -quit)
```suggestion
ZIP_PATH=$(find . -name "${ZIP_FILE}" -print -quit)
```

2024-08-18 00:23 UTC, nutti commented on tools/pip_package/run_ruff_flake8_pyi.sh
> +fi
```suggestion
if [ -z "${ZIP_PATH}" ]; then
    echo "No matching zip file found for Blender version ${BLENDER_VERSION}"
    exit 1
fi
```

2024-08-18 00:23 UTC, nutti commented on tools/pip_package/run_ruff_flake8_pyi.sh
> +unzip -q "$ZIP_PATH" -d "$EXTRACT_DIR"
```suggestion
mkdir -p "${EXTRACT_DIR}"
unzip -q "${ZIP_PATH}" -d "{$EXTRACT_DIR}"
```

2024-08-18 00:23 UTC, nutti commented on tools/pip_package/run_ruff_flake8_pyi.sh
> +ruff check "$EXTRACT_DIR" --select=PYI --ignore=PYI011,PYI014,PYI018,PYI021,PYI054
```suggestion
ruff check "${EXTRACT_DIR}" --select=PYI --ignore=PYI011,PYI014,PYI018,PYI021,PYI054
```

2024-08-18 00:23 UTC, nutti commented on tools/pip_package/run_ruff_flake8_pyi.sh
> +rm -rf "$EXTRACT_DIR"
```suggestion
rm -rf "${EXTRACT_DIR}"
```

2024-09-15 08:30 UTC, nutti approved these changes
@JonathanPlasse 
From the discussion on Discord, I applied my suggested changes.

2024-09-15 08:52 UTC, merged