Update: Create type aliases for rna enums
nutti/fake-bpy-module pull request #300
Opened 2024-08-11 15:57 UTC by JonathanPlasse

### Purpose of the pull request

- Follow up to #295

### Description about the pull request

*The description about this pull request.*

### Additional comments** [Optional]

2024-08-11 18:06 UTC, JonathanPlasse commented
Should I create a new node to use the PEP 695 `type` syntax instead?

2024-08-12 05:04 UTC, nutti reviewed
@JonathanPlasse 

Thank you for your suggestion.
Your suggestion looks good to me.
But some CI tests are failed, please check failed test result.

2024-08-12 05:07 UTC, nutti commented
> Should I create a new node to use the PEP 695 `type` syntax instead?

Could you show me the mock generated code?
To solve #161, it seems necessary to do this.

2024-08-12 07:15 UTC, Andrej730 commented
It would be nice if we could put `OperatorReturnItems` it in some other module and not `bpy.types` to emphasize that Blender doesn't have it originally. Maybe `bpy.typing`?

2024-08-14 22:41 UTC, JonathanPlasse commented
The CI was failing because the `type` syntax is Python 3.12+ only.

I move the enum literal types to `bpy.typing` like suggested.
Enum type must be imported with `from bpy.typing import <EnumItemType>` as `typing` is not present in `bpy.__init__.py`.
Here is a snapshot of the generated code of `bpy.typing`.
![Screenshot from 2024-08-15 00-33-24](https://github.com/user-attachments/assets/9163e5e0-ee59-4d21-9e15-02802a555b83)

2024-08-16 09:00 UTC, nutti requested changes
@JonathanPlasse 

Thank you for your hard work! The proposal is fine.
But we need to change the code to consider the code structure for the future maintenance.
Please do not hesitate to consult to me if you will face with the difficult issue.

2024-08-16 09:24 UTC, JonathanPlasse commented on src/fake_bpy_module/transformer/data_type_refiner.py
> +def generate_rna_enum_items() -> str:
I understand. I will look into it.

2024-09-15 08:58 UTC, nutti commented on src/gen_module.sh
> +# fi
Reverted this code by my commit.

2024-09-15 09:11 UTC, nutti commented on src/fake_bpy_module/transformer/data_type_refiner.py
> +def generate_rna_enum_items() -> str:
I resolved this comment for now.
Will resolve it a following commits.

2024-09-15 09:13 UTC, nutti approved these changes

2024-09-15 09:15 UTC, merged

2024-09-21 06:52 UTC, nutti commented on src/fake_bpy_module/transformer/data_type_refiner.py
> +def generate_rna_enum_items() -> str:
@JonathanPlasse 
b830e64fddbb3e3a1ede8ef39ec4ba688d42a980 solved this conversation.
Thank you for tackling this PR.

2024-09-23 08:53 UTC, JonathanPlasse commented on src/fake_bpy_module/transformer/data_type_refiner.py
> +def generate_rna_enum_items() -> str:
@nutti, Awesome, thank you very much.